# Generated by Django 5.0.4 on 2024-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyblo_app', '0002_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='key',
            field=models.TextField(default=None, max_length=5000),
        ),
    ]
