# Generated by Django 5.0.4 on 2024-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyblo_app', '0003_file_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='key',
        ),
        migrations.AddField(
            model_name='file',
            name='last_checked_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='last_checked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='last_read_position',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='service_account_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
