# Generated by Django 5.0.4 on 2024-05-18 13:55

import cyblo.cyblo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyblo_app', '0004_remove_file_key_file_last_checked_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[(cyblo.cyblo_app.models.LogType['SQL'], 'SQL'), (cyblo.cyblo_app.models.LogType['XSS'], 'XSS'), (cyblo.cyblo_app.models.LogType['DDOS'], 'DDOS'), (cyblo.cyblo_app.models.LogType['ANOMALY'], 'Anomaly'), (cyblo.cyblo_app.models.LogType['NONE'], 'None')], default='None', max_length=20),
        ),
    ]
