# Generated by Django 5.0.4 on 2024-05-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyblo_app', '0005_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='type',
        ),
    ]
