# Generated by Django 5.0.4 on 2024-05-25 12:07

import cyblo.cyblo_app.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyblo_app', '0006_remove_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDBConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('database', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[(cyblo.cyblo_app.models.LogType['SQL'], 'SQL'), (cyblo.cyblo_app.models.LogType['XSS'], 'XSS'), (cyblo.cyblo_app.models.LogType['DDOS'], 'DDOS'), (cyblo.cyblo_app.models.LogType['ANOMALY'], 'Anomaly'), (cyblo.cyblo_app.models.LogType['NONE'], 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='cyblo_app.file'),
        ),
        migrations.AddField(
            model_name='log',
            name='external_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='cyblo_app.externaldbconnection'),
        ),
    ]
