# Generated by Django 5.0.4 on 2024-05-25 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyblo_app', '0007_externaldbconnection_log_log_type_alter_log_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldbconnection',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='external_db_connections', to='cyblo_app.project'),
        ),
        migrations.AddField(
            model_name='externaldbconnection',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='external_db_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
